# Generated by Django 3.2.2 on 2021-05-23 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("for_sale", "For sale"), ("to_rent", "To rent")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("url", models.URLField(null=True)),
                ("thumbnail", models.URLField(null=True)),
                ("title", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("price", models.IntegerField(null=True)),
                ("date", models.DateTimeField(null=True)),
                ("agent_name", models.CharField(max_length=50, null=True)),
                ("agent_phone", models.CharField(max_length=50, null=True)),
                ("agent_address", models.CharField(max_length=100, null=True)),
                ("property_type", models.CharField(max_length=25, null=True)),
                ("bedrooms", models.IntegerField(null=True)),
                ("bathrooms", models.IntegerField(null=True)),
                ("receptionrooms", models.IntegerField(null=True)),
                ("sqft", models.CharField(max_length=15, null=True)),
                ("description", models.TextField(null=True)),
                ("key_features", models.JSONField(null=True)),
                (
                    "cordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326
                    ),
                ),
            ],
            options={"verbose_name": "Property", "verbose_name_plural": "Properties"},
        )
    ]
