repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
        stages: [commit]
  - repo: https://github.com/ambv/black
    rev: 21.4b2
    hooks:
      - id: black
        types_or: [python, pyi]
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        entry: flake8 --max-line-length=127
        stages: [commit]
