version: "3.8"
services:
  backend:
    build: backend
    container_name: willos_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
      - static_volume:/backend/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
  celery:
    build: backend
    container_name: willos_celery
    command: celery -A backend worker -l INFO
    volumes:
      - ./backend:/backend
      - static_volume:/backend/static
    env_file:
      - .env
    depends_on:
      - backend
      - rabbitmq
  rabbitmq:
    container_name: willos_mq
    image: "rabbitmq:3.8-alpine"
    ports:
      - 5672:5672
    env_file:
      - .env
  db:
    image: "postgis/postgis:13-master"
    container_name: willos_db
    volumes:
      - willos-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
volumes:
  static_volume:
  willos-pgdata:
