version: "3.8"
services:
  backend:
    build: backend
    volumes:
      - ./backend:/backend
      - static_volume:/backend/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: "postgis/postgis:13-master"
    volumes:
      - willos-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
volumes:
  static_volume:
  willos-pgdata:
