# Generated by Django 3.2.2 on 2021-07-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="facebook_user_id", new_name="fb_user_id"
        ),
        migrations.RemoveField(model_name="user", name="type_2fa"),
        migrations.AlterField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
