on: [push, pull_request]
name: main
jobs:
  black-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: jpetrucciani/black-check@master
  flake8-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: tonybajan/flake8-check-action@v1.0.0
        with:
          select: E3,E4,E5,E7,W6,F,B,G0
          maxlinelength: 127
          repotoken: ${{ secrets.GITHUB_TOKEN }}
